module.exports = [
  { name: 'deep sea port', connects: ['heros square', 'shady path'] },
  { name: 'shady path', connects: ['deep sea port', 'twilight alley'] },
  {
    name: 'heros square',
    connects: [
      'deep sea port',
      'twilight alley',
      'bustling market',
      'caligrase sewers',
      'deltis keep',
      'golden dragon ruins',
      'aria reservoir',
      'temple of oblivion',
      'old sewers',
      'underground dragoon ruins',
      'descension ruins',
      'roswald deep fort',
      'ruined chamber',
      'facility 13',
      'dark roundtable',
      'sangent ruins',
    ],
  },
  { name: 'twilight alley', connects: ['heros square'] },
  {
    name: 'bustling market',
    connects: ['heros square', 'ministry of arcanum'],
  },
  { name: 'ministry of arcanum', connects: ['bustling market'] },
  { name: 'caligrase sewers', connects: ['heros square'] },
  { name: 'deltis keep', connects: ['heros square'] },
  { name: 'golden dragon ruins', connects: ['heros square'] },
  { name: 'aria reservoir', connects: ['heros square'] },
  { name: 'temple of oblivion', connects: ['heros square'] },
  { name: 'old sewers', connects: ['heros square'] },
  { name: 'underground dragoon ruins', connects: ['heros square'] },
  { name: 'descension ruins', connects: ['heros square'] },
  { name: 'roswald deep fort', connects: ['heros square'] },
  { name: 'ruined chamber', connects: ['heros square'] },
  { name: 'facility 13', connects: ['heros square'] },
  { name: 'dark roundtable', connects: ['heros square'] },
  { name: 'sangent ruins', connects: ['heros square'] },
];
